/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'text-ivoire-orange', 'text-ivoire-vert', 'text-ivoire-gris', 'text-ivoire-nuit', 'text-ivoire-texte', 'text-ivoire-rouge', 'text-ivoire-bleu',
    'bg-ivoire-orange', 'bg-ivoire-vert', 'bg-ivoire-gris', 'bg-ivoire-nuit', 'bg-ivoire-blanc', 'bg-ivoire-beige',
    'bg-ivoire-orange/10', 'bg-ivoire-vert/10', 'bg-ivoire-gris/10', 'bg-ivoire-rouge/10',
    'bg-ivoire-orange/15', 'bg-ivoire-vert/15',
    'bg-error', 'bg-error/10', 'bg-error/15', 'text-error',
    'bg-error-container', 'bg-error-container/40',
    'bg-surface-container-high', 'bg-surface-container',
    'bg-amber-500', 'text-amber-500', 'bg-amber-500/10',
  ],
  theme: {
    extend: {
      colors: {
        ivoire: {
          orange: '#E8611A',
          'orange-dark': '#C94E0F',
          vert: '#0B7A3E',
          'vert-clair': '#16A34A',
          blanc: '#FAF8F3',
          beige: '#F4EFE6',
          gris: '#6B7280',
          'gris-carte': '#4B5563',
          nuit: '#0D1B2A',
          texte: '#1E293B',
          frontiere: '#CBD5E1',
          rose: '#EC4899',
          bleu: '#2563EB',
          rouge: '#DC2626',
        },
        surface: { DEFAULT: '#F4EFE6', 'container-low': '#f0f3ff', container: '#e7eeff', 'container-high': '#dee8ff', 'container-highest': '#d8e3fb' },
        primary: { DEFAULT: '#E8611A', container: '#C94E0F', fixed: '#ffdbcd' },
        secondary: { DEFAULT: '#0B7A3E', container: '#93f5ab' },
        error: { DEFAULT: '#ba1a1a', container: '#ffdad6' },
      },
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
      fontSize: {
        'headline-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '700' }],
        'headline-md': ['1.375rem', { lineHeight: '1.3', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['2rem', { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '900' }],
        'headline-lg-mobile': ['1.5rem', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '900' }],
        'kpi-metric': ['2.5rem', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '900' }],
        'kpi-metric-mobile': ['1.875rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '900' }],
        'label-sm': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['0.875rem', { lineHeight: '1.25', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.65', fontWeight: '400' }],
      },
      boxShadow: { card: '0 4px 24px rgba(0,0,0,0.06)', sheet: '0 -4px 20px rgba(0,0,0,0.08)', halo: '0 0 20px rgba(232,97,26,0.35)', nav: '0 -4px 20px rgba(0,0,0,0.06)' },
      animation: { 'fade-in-up': 'fadeInUp 300ms ease-out', 'slide-up': 'slideUp 500ms cubic-bezier(0.4,0,0.2,1)' },
      keyframes: {
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { '0%': { transform: 'translateY(100%)' }, '100%': { transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
};
