-- Migration: Étend la table collectes avec les champs du formulaire terrain complet
-- À exécuter sur les bases existantes

ALTER TABLE public.collectes
  ADD COLUMN IF NOT EXISTS district TEXT,
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS departement TEXT,
  ADD COLUMN IF NOT EXISTS sous_prefecture TEXT,
  ADD COLUMN IF NOT EXISTS localite TEXT,
  ADD COLUMN IF NOT EXISTS milieu TEXT CHECK (milieu IN ('urbain', 'rural')),
  ADD COLUMN IF NOT EXISTS voie_acces TEXT CHECK (voie_acces IN ('goudron', 'piste_praticable', 'piste_saisonniere')),
  ADD COLUMN IF NOT EXISTS nom_ecole TEXT,
  ADD COLUMN IF NOT EXISTS statut_juridique TEXT CHECK (statut_juridique IN ('public', 'prive_laic', 'prive_confessionnel', 'communaute')),
  ADD COLUMN IF NOT EXISTS niveau_enseignement TEXT CHECK (niveau_enseignement IN ('primaire', 'secondaire', 'superieur')),
  ADD COLUMN IF NOT EXISTS annee_creation INTEGER,
  ADD COLUMN IF NOT EXISTS annee_scolaire TEXT,
  ADD COLUMN IF NOT EXISTS salles_fonctionnelles INTEGER,
  ADD COLUMN IF NOT EXISTS nb_enseignants_presents INTEGER,
  ADD COLUMN IF NOT EXISTS deficit_enseignants BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS nb_enseignants_manquants INTEGER,
  ADD COLUMN IF NOT EXISTS classes_jumelees BOOLEAN,
  ADD COLUMN IF NOT EXISTS matieres_penurie JSONB,
  ADD COLUMN IF NOT EXISTS materiaux_batiment TEXT CHECK (materiaux_batiment IN ('parpaing_ciment', 'brique_terre', 'bois', 'boue_banco', 'paillote')),
  ADD COLUMN IF NOT EXISTS presence_cloture BOOLEAN,
  ADD COLUMN IF NOT EXISTS securite_routiere BOOLEAN,
  ADD COLUMN IF NOT EXISTS nb_latrines INTEGER,
  ADD COLUMN IF NOT EXISTS eau_potable BOOLEAN,
  ADD COLUMN IF NOT EXISTS source_eau_village TEXT CHECK (source_eau_village IN ('sodeci', 'forage_village', 'aucun')),
  ADD COLUMN IF NOT EXISTS localite_raccordee_elec BOOLEAN,
  ADD COLUMN IF NOT EXISTS ecole_electrifiee BOOLEAN,
  ADD COLUMN IF NOT EXISTS source_energie TEXT CHECK (source_energie IN ('reseau_cie', 'panneaux_solaires', 'groupe_electrogene')),
  ADD COLUMN IF NOT EXISTS poteau_100m BOOLEAN,
  ADD COLUMN IF NOT EXISTS cantine_fonctionnelle BOOLEAN,
  ADD COLUMN IF NOT EXISTS source_cantine TEXT CHECK (source_cantine IN ('unicef_pam', 'parents', 'collectivite'));
